[platformio]
default_envs = esp32dev

[common]
lib_deps =
  miguelbalboa/MFRC522@^1.4.12
  https://github.com/mobizt/Firebase-ESP-Client.git
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = ${common.lib_deps}

[env:board-esp32-devkit-c-v4]
platform = espressif32
board = board-esp32-devkit-c-v4
framework = arduino
monitor_speed = 115200
lib_deps = ${common.lib_deps}
